// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqR6h6WZpf9Q_IqMcyi4-cQkEMIg8zI6c',
    appId: '1:481617313791:web:9ba2aaef8461fe8ac1b1ca',
    messagingSenderId: '481617313791',
    projectId: 'floralshieldai',
    authDomain: 'floralshieldai.firebaseapp.com',
    storageBucket: 'floralshieldai.firebasestorage.app',
    measurementId: 'G-FM7DVFTJY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJT9sykSTaIUg5x73Sed-A7hBw3S_cy3A',
    appId: '1:481617313791:android:f534def0e0d662a4c1b1ca',
    messagingSenderId: '481617313791',
    projectId: 'floralshieldai',
    storageBucket: 'floralshieldai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuoPEsodCRmH2_kzq140-5PjMvpWSs0TI',
    appId: '1:481617313791:ios:cb7f71b53ac44988c1b1ca',
    messagingSenderId: '481617313791',
    projectId: 'floralshieldai',
    storageBucket: 'floralshieldai.firebasestorage.app',
    iosBundleId: 'com.example.plantDiseaseDetector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuoPEsodCRmH2_kzq140-5PjMvpWSs0TI',
    appId: '1:481617313791:ios:cb7f71b53ac44988c1b1ca',
    messagingSenderId: '481617313791',
    projectId: 'floralshieldai',
    storageBucket: 'floralshieldai.firebasestorage.app',
    iosBundleId: 'com.example.plantDiseaseDetector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqR6h6WZpf9Q_IqMcyi4-cQkEMIg8zI6c',
    appId: '1:481617313791:web:cfde671b521cb22bc1b1ca',
    messagingSenderId: '481617313791',
    projectId: 'floralshieldai',
    authDomain: 'floralshieldai.firebaseapp.com',
    storageBucket: 'floralshieldai.firebasestorage.app',
    measurementId: 'G-SHF005GDVR',
  );
}
