import 'dart:io';
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import '../services/kml_service.dart';
import '../theme/app_theme.dart';

class DroneExportScreen extends StatefulWidget {
  const DroneExportScreen({super.key});

  @override
  State<DroneExportScreen> createState() => _DroneExportScreenState();
}

class _DroneExportScreenState extends State<DroneExportScreen> {
  final TextEditingController _widthController = TextEditingController(text: '100');
  final TextEditingController _lengthController = TextEditingController(text: '100');
  final TextEditingController _swathController = TextEditingController(text: '4');

  bool _isGenerating = false;

  double _parse(TextEditingController c, double fallback) {
    final v = double.tryParse(c.text.trim());
    return (v == null || v <= 0) ? fallback : v;
  }

  int get _passCount {
    final width = _parse(_widthController, 100);
    final swath = _parse(_swathController, 4);
    return (width / swath).ceil().clamp(1, 200);
  }

  Future<void> _generateAndShare() async {
    setState(() => _isGenerating = true);
    try {
      final serviceEnabled = await Geolocator.isLocationServiceEnabled();
      if (!serviceEnabled) {
        throw Exception('Location services are off. Enable location and try again.');
      }

      LocationPermission permission = await Geolocator.checkPermission();
      if (permission == LocationPermission.denied) {
        permission = await Geolocator.requestPermission();
      }
      if (permission == LocationPermission.denied || permission == LocationPermission.deniedForever) {
        throw Exception('Location permission is required to center the flight path.');
      }

      final position = await Geolocator.getCurrentPosition(
        desiredAccuracy: LocationAccuracy.high,
      );

      final width = _parse(_widthController, 100);
      final length = _parse(_lengthController, 100);
      final swath = _parse(_swathController, 4);

      final waypoints = KmlService.generateCoveragePath(
        centerLat: position.latitude,
        centerLng: position.longitude,
        widthMeters: width,
        lengthMeters: length,
        swathMeters: swath,
      );
      final kml = KmlService.buildKml(waypoints: waypoints, name: 'FloraShield Flight Path');

      final dir = await getTemporaryDirectory();
      final file = File('${dir.path}/floralshield_flight_path_${DateTime.now().millisecondsSinceEpoch}.kml');
      await file.writeAsString(kml);

      await Share.shareXFiles(
        [XFile(file.path)],
        text: 'Drone coverage flight path generated by FloraShield AI',
      );
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(e.toString().replaceFirst('Exception: ', '')),
            backgroundColor: AppColors.neonRed,
          ),
        );
      }
    } finally {
      if (mounted) setState(() => _isGenerating = false);
    }
  }

  @override
  void dispose() {
    _widthController.dispose();
    _lengthController.dispose();
    _swathController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        decoration: AppTheme.backgroundGradient,
        child: SafeArea(
          child: SingleChildScrollView(
            padding: const EdgeInsets.fromLTRB(18, 8, 18, 32),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    GestureDetector(
                      onTap: () => Navigator.of(context).pop(),
                      child: const Icon(Icons.arrow_back, color: AppColors.textPrimary),
                    ),
                    const SizedBox(width: 14),
                    Text('Drone Flight Path', style: AppTextStyles.heading(size: 18)),
                  ],
                ),
                const SizedBox(height: 18),

                Container(
                  padding: const EdgeInsets.all(14),
                  decoration: BoxDecoration(
                    color: AppColors.neonAmber.withOpacity(0.10),
                    borderRadius: BorderRadius.circular(14),
                    border: Border.all(color: AppColors.neonAmber.withOpacity(0.3)),
                  ),
                  child: Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Icon(Icons.info_outline, color: AppColors.neonAmber, size: 18),
                      const SizedBox(width: 10),
                      Expanded(
                        child: Text(
                          'This app has no field-boundary mapping yet, so this generates a simple rectangular coverage pattern centered on your current GPS location - not a true surveyed field boundary. Review it in your drone software before flying.',
                          style: AppTextStyles.body(size: 12, color: AppColors.textPrimary),
                        ),
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 20),

                Text('Coverage width (meters, east-west)', style: AppTextStyles.body(size: 13, color: AppColors.textSecondary)),
                const SizedBox(height: 8),
                GlassCard(
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
                  child: TextField(
                    controller: _widthController,
                    onChanged: (_) => setState(() {}),
                    keyboardType: const TextInputType.numberWithOptions(decimal: true),
                    style: AppTextStyles.heading(size: 18),
                    decoration: const InputDecoration(
                      border: InputBorder.none,
                      hintText: 'e.g. 100',
                      suffixText: 'm',
                    ),
                  ),
                ),
                const SizedBox(height: 16),

                Text('Coverage length (meters, north-south)', style: AppTextStyles.body(size: 13, color: AppColors.textSecondary)),
                const SizedBox(height: 8),
                GlassCard(
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
                  child: TextField(
                    controller: _lengthController,
                    onChanged: (_) => setState(() {}),
                    keyboardType: const TextInputType.numberWithOptions(decimal: true),
                    style: AppTextStyles.heading(size: 18),
                    decoration: const InputDecoration(
                      border: InputBorder.none,
                      hintText: 'e.g. 100',
                      suffixText: 'm',
                    ),
                  ),
                ),
                const SizedBox(height: 16),

                Text('Drone spray swath width (meters)', style: AppTextStyles.body(size: 13, color: AppColors.textSecondary)),
                const SizedBox(height: 8),
                GlassCard(
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
                  child: TextField(
                    controller: _swathController,
                    onChanged: (_) => setState(() {}),
                    keyboardType: const TextInputType.numberWithOptions(decimal: true),
                    style: AppTextStyles.heading(size: 18),
                    decoration: const InputDecoration(
                      border: InputBorder.none,
                      hintText: 'e.g. 4',
                      suffixText: 'm',
                    ),
                  ),
                ),
                const SizedBox(height: 20),

                GlassCard(
                  child: Row(
                    children: [
                      const Icon(Icons.route_outlined, color: AppColors.neonGreen, size: 20),
                      const SizedBox(width: 12),
                      Expanded(
                        child: Text(
                          '$_passCount coverage pass${_passCount == 1 ? '' : 'es'} will be generated',
                          style: AppTextStyles.body(size: 13, weight: FontWeight.w600),
                        ),
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 24),

                SizedBox(
                  width: double.infinity,
                  height: 52,
                  child: ElevatedButton.icon(
                    onPressed: _isGenerating ? null : _generateAndShare,
                    icon: _isGenerating
                        ? const SizedBox(
                      width: 16,
                      height: 16,
                      child: CircularProgressIndicator(strokeWidth: 2, color: AppColors.bgDark),
                    )
                        : const Icon(Icons.airplanemode_active_outlined, size: 18),
                    label: Text(_isGenerating ? 'Generating...' : 'Generate & Share Flight Path (.KML)'),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}